from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class MemoryBackend(Protocol):
    def remember(self, key: str, value: Any, session_id: str) -> None: ...
    def recall(self, key: str, session_id: str) -> Any | None: ...
    def search(self, query: str, session_id: str, k: int = 5) -> list[dict]: ...
    def consolidate(self, session_id: str) -> None: ...
